import './globals.css'
import type { Metadata } from 'next'
import Navbar from "@/app/components/navbar";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="he">
      <body>
      <header>
        <Navbar/>
      </header>
      {children}
      </body>
    </html>
  )
}
